### PR TITLE
Database design in readme

### PR DESCRIPTION
**Pull request by lduran2**

### CODE REVIEW

**Comment by lduran2** [comment]
@Shanegrinkewitz I added to the `README` describing the database files. I remember you requested this information, which I sent to you before. However, I figured this would be good for the README as well.

The merge conflict involves package-lock.json, which I will fix later. However, please let me know if these are good changes to the README.

**Review by Shanegrinkewitz — APPROVED** [review]
The changes to the readme are good.

**Comment by lduran2** [comment]
Moved to https://github.com/Capstone-Projects-2022-Spring/project-lexicallearner/pull/28

**Comment by lduran2** [comment]
Thank you, @Shanegrinkewitz! Pushing to [Sp](https://github.com/Capstone-Projects-2022-Spring/project-lexicallearner/tree/sprint6)

**Pull request closed without merging**
